AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 25
  Exclude:
    - cerberus.gemspec
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'db/migrate/*.rb'
